### ISSUE TITLE
statistics get confused by overlapping journeys

### ISSUE THREAD

**Issue by marudor** [derf/travelynx#11]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1881725/56868457-f7171d00-69f2-11e9-9679-377f9af31bff.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/1881725/56868461-f9797700-69f2-11e9-84ca-f2d6164fcda4.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1881725/56868464-faaaa400-69f2-11e9-9d0c-f51815697d79.png">

Here we have March, April and yearly.
March + April should requal yearly.
Your "Wartezeit" overflows though.

**Comment by marudor** [comment]
Problem found. Overlapping travel times.

**Comment by derf** [comment]
turns out that  travelynx' statistics get confused by overlapping travel times (e.g. a journey from 16:00 to 17:00 followed by a journey from 16:10 to 16:30 resulting in -30 minutes interchange time). Although this is more or less a user error (nonsense in, nonsense out), it should never lead to this kind of confusion and instead result in a warning.
