### ISSUE TITLE
Only linear distances available

### ISSUE THREAD

**Issue by Ein-Tim** [derf/travelynx#119]
I noticed today that, on a trip from München Karlsplatz (Stachus) -> München Harras, only the linear distance is available in the travelynx map:
![image](https://github.com/derf/travelynx/assets/67682506/2eb957e4-cb43-42ff-92f9-93a28a400113)

I've done the same route one week ago and for this trip there's the detailed distance available:
![image](https://github.com/derf/travelynx/assets/67682506/efbacd98-d826-4cef-9d9f-5006bc346275)

This seems like a bug.

**Comment by Ein-Tim** [comment]
Link to today's trip: https://travelynx.de/p/Ein-Tim/j/637653?token=8004135-219-1708357680

Link to the trip I made one week ago: https://travelynx.de/p/Ein-Tim/j/625956?token=8004132-22-1707659400

Both times I used the "DB Regio S-Bahn München".

**Comment by Ein-Tim** [comment]
Seems to be fixed.

**Comment by Ein-Tim** [comment]
@derf Could you please reopen this? This seems to happen irregularly, just encountered it again: 3 km mit BRB 86945 – Ankunft pünktlich um 19:32 https://travelynx.de/p/Ein-Tim/j/648350?token=8004128-207-1708972140

**Comment by derf** [comment]
That happens whenever you check in via "Nahverkehr" (HAFAS) rather than "Schienenverkehr" (IRIS). It's a mixture of sub-optimal UI naming and backend differences.

Known issue, working on it, can't provide an ETA though. Until then, please make sure to check in via Schienenverkehr if possible and only use Nahverkehr for modes of transport that are not available in the Schienenverkehr backend. Unfortunately, that issue also touches the check-in suggestions travelynx shows when still checked into a train.

**Comment by Ein-Tim** [comment]
@derf Ah, okay, I see! Thank you for mentioning the work-around, I will make sure to use IRIS whenever possible! Have a nice evening.
